<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $reportTitle }}</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; margin: 0; padding: 0; }
        .header-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .header-table td { vertical-align: middle; }
        .info-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; border: 1px solid #000; }
        .info-table th { background-color: #f2f2f2; border: 1px solid #000; font-size: 12px; padding: 8px; text-align: center; }
        .info-table td { border: 1px solid #000; padding: 5px; font-size: 11px; text-align: left; }
        .entryTable { width: 100%; border-collapse: collapse; border: 1px solid #000; margin-bottom: 30px; }
        .entryTable thead th { background-color: #f2f2f2; border: 1px solid #000; font-size: 10px; padding: 8px; text-align: center; }
        .entryTable tbody td { border: 1px solid #000; padding: 5px; font-size: 11px; text-align: center; }
        .text-left { text-align: left !important; padding-left: 10px !important; }
        .footer { margin-top: 30px; font-size: 10px; text-align: center; color: #777; }
        h3 { font-size: 12px; text-transform: uppercase; margin-bottom: 5px; }
    </style>
</head>
<body>
    <div class="header-table">
        <table style="width: 100%;">
            <tr>
                <td style="width: 20%; text-align: right;"><img src="{{ public_path('helpdesk-logo.png') }}" alt="Logo" width="80"></td>
                <td style="text-align: center; font-size: 14px; width: 60%;">
                    <p style="margin: 0">Republic of the Philippines</p>
                    <p style="margin: 0; font-weight: bold;">IT HELP DESK</p>
                    <p style="margin: 0">East Ave. cor. NIA Rd., Diliman, Quezon City</p>
                </td>
                <td style="width: 20%; text-align: right; vertical-align: top;">
                    <p style="margin: 0; font-size: 12px; font-weight: bold; text-align: left;">{{ $reportTitle }}</p>
                    <p style="margin: 2; font-size: 11px;text-align: left;">Generated Date:<br> {{ now()->timezone('Asia/Manila')->format('F j, Y, g:i a') }}</p>
                </td>
            </tr>
        </table>
    </div>

    <table class="info-table">
        <thead>
            <tr><th colspan="4" style="text-transform:uppercase;">{{$reportTitle}}</th></tr> 
        </thead>
        <tbody>
            <tr>
                <td colspan="2"><strong>Generated by:</strong> {{ auth()->user()->Firstname ?? 'System' }}</td>
                <td colspan="2"><strong>Report Period:</strong> {{ $reportPeriod }}</td>
            </tr>
            <tr>
                <td colspan="4"><strong>Department Office Code:</strong> {{ $officeCode }}</td>
            </tr>
        </tbody>
    </table>

    <h3>MOST CANCELLED ACTIVITY SPECIFICATION</h3>
    <table class="entryTable">
        <thead>
            <tr>
                @foreach($table1['headers'] as $header)
                    <th @if($loop->first) class="text-left" @endif>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($table1['rows'] as $label => $values)
                <tr>
                    <td class="text-left"><strong>{{ $label }}</strong></td>
                    @foreach($values as $value)
                        <td>{{ $value }}</td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <h3>CANCELLATION REASON PER DEPARTMENT</h3>
    <table class="entryTable">
        <thead>
            <tr>
                @foreach($table2['headers'] as $header)
                    <th @if($loop->first) class="text-left" @endif>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($table2['rows'] as $label => $values)
                <tr>
                    <td class="text-left"><strong>{{ $label }}</strong></td>
                    @foreach($values as $value)
                        <td>{{ $value }}</td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">Page generated by {{ config('app.name') }}</div>
</body>
</html>